name: Deploy to Koyeb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/install-koyeb-cli@v2
        with:
          api_token: ${{ secrets.KOYEB_API_KEY }}

      - name: Redeploy to Koyeb
        run: |
          koyeb login --api-key ${{ secrets.KOYEB_API_KEY }}
          koyeb service redeploy ame/bookfinderbot-webhook
