name: Auto Redeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Install Koyeb CLI
        run: curl https://cli.koyeb.com/install | sh

      - name: Build and deploy the application
        run: |
          go build -o myapp main.go
          koyeb login --api-key ${{ secrets.KOYEB_API_KEY }}
          koyeb deploy --app myapp --buildpack golang --path . --version latest
